services:
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=flaskuser
      - MYSQL_PASSWORD=flaskpass
      - MYSQL_DB=flaskdb
      - MYSQL_PORT=3309
    volumes:
      - ./app:/app
    depends_on:
      - mysql-db
    networks:
      - flask-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=flaskdb
      - MYSQL_USER=flaskuser
      - MYSQL_PASSWORD=flaskpass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge

volumes:
  mysql-data:
